version: '3.9'

services:
  postgres-dev:
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      # This points to the environment file
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  postgres-test:
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT_TEST}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_TEST}

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:5050

volumes:
  pg_data: