version: '3.9'

services:
  postgres-dev:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      # This points to the environment file
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  postgres-test:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    env_file:
      # This points to the environment file
      - .env

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:5050

volumes:
  pg_data: